# -*- coding: utf-8 -*-
"""Assignment#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZCu4DZ5thogAEkzIekgPtKAaIiQJhzF
"""



"""#Question#1"""

P= int(input('Enter the principal :'))
R = float(input('Enter the rate of interest :'))
r = R *0.01
t = float(input('Enter the number of years :'))

A = P * (1+ r*t)
print('After {} years at {}%, the investment will be worth $'.format(t,R), A)

"""#Question#2"""

order = float(input('What is the order amount?'))
state = input('What is the state?')
if state == 'MN':
  print ('The total is $',order)
else:
  print('The subtotal is $', order)
  print('The tax is 0.55')
  print('The total is $', order + 0.55)

"""#Question#3"""

pas = (input('What is the password?'))
password = 'Muhammad_Suleman_Tunio@IBA'
if pas == password:
  print('Welcome!')
else:
  print('I dont know you.')

"""#Question#4"""

age = int(input('What is your age? '))
if age < 16:
  print('You are not old enough to legally derive.')
else:
  print('You are old enough to legally derive.')

"""#Question#5"""

print('Press C to convert from Fahrenheit to Celsius.')
print('Press F to convert from celsius to Fahrenheit.')

choice = input('Your choice: ', )


if choice == 'C':
  f = float(input('Please enter the temprature in Fahrenheit: '))
  f_c = (f-32) *(5/9)
  print('The temperature in Celsius is',f_c, '.')
else:
  c = float(input('Please enter the temprature in Celsius: '))
  c_f = (c *(9/5)) + 32
  print('The temperature in Fahrenheit is',c_f, '.')

